# Generated by Django 4.2.7 on 2023-12-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
