# Generated by Django 4.2.7 on 2023-12-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='kind',
            field=models.CharField(max_length=128),
        ),
    ]
