# Generated by Django 4.2.7 on 2023-12-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='statas',
            new_name='alert',
        ),
    ]
